name: sample
on:
  push:
    branches: ["main"]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4
      - name: just run normal printing
        run: echo "hello world!""
